-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    price money,
    stock integer,
    state text COLLATE pg_catalog."default",
    "idCategory" integer,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."shoppingCart"
(
    "idProduct" integer NOT NULL,
    quantity integer,
    "idUser" integer NOT NULL,
    CONSTRAINT "shoppingCart_pkey" PRIMARY KEY ("idProduct", "idUser")
);

CREATE TABLE IF NOT EXISTS public."typeUser"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    CONSTRAINT "typeUser_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    "idTypeUser" integer,
    "creationDate" date,
    "updateDate" date,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT user_u UNIQUE (email)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_fkey_category FOREIGN KEY ("idCategory")
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."shoppingCart"
    ADD CONSTRAINT "shoppingCart_fkey_product" FOREIGN KEY ("idProduct")
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."shoppingCart"
    ADD CONSTRAINT "shoppingCart_fkey_user" FOREIGN KEY ("idUser")
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT "user_fkey_typeUser" FOREIGN KEY ("idTypeUser")
    REFERENCES public."typeUser" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;